name: bazar
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_native_splash: ^2.4.6
  google_fonts: ^6.3.2
  smooth_page_indicator: ^1.2.1
  stacked: ^3.4.0
  stacked_services: ^1.1.0


  
dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  golden_toolkit: ^0.15.0

  

flutter:
  uses-material-design: true
  assets: 
    - assets/img/

flutter_native_splash:
  color: "#352368"
  image: assets/img/bazar_logo_white.png

  android: true
  android_gravity: center

  android_12:
    color: "#54408C"
    image: assets/img/bazar_logo_splash.png
    
  ios: true
  ios_content_mode: scaleAspectFit

    

